### ISSUE TITLE
Error on snap after connection to admin WiFi

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni-user/CBJ_Security-Bear_Snap#1]
``` dart
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: Unhandled exception:
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: ProcessException: Permission denied
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]:   Command: ip route
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #1      Process.start (dart:io-patch/process_patch.dart:36)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #3      Process.run (dart:io-patch/process_patch.dart:47)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #4      NetworkActions.getDefaultGateway (package:security_bear/features/security_bear/application/usecases/network_actions/network_actions.dart:226)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #5      NetworkActions.connectToAdminWhenExist (package:security_bear/features/security_bear/application/usecases/network_actions/network_actions.dart:78)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: <asynchronous suspension>
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: #6      SecurityBearManagerU.manegeNetworkConnection (package:security_bear/features/security_bear/application/usecases/core_u/security_bear_manager.dart:38)
2021-12-30T20:05:21+02:00 security-bear.security-bear[16290]: <asynchronous suspension>
2021-12-30T20:05:21+02:00 systemd[1]: snap.security-bear.security-bear.service: Main process exited, code=exited, status=255/EXCEPTION
2021-12-30T20:05:21+02:00 systemd[1]: snap.security-bear.security-bear.service: Failed with result 'exit-code'.
2021-12-30T20:05:21+02:00 systemd[1]: snap.security-bear.security-bear.service: Scheduled restart job, restart counter is at 5.
2021-12-30T20:05:21+02:00 systemd[1]: Stopped Service for snap application security-bear.security-bear.
2021-12-30T20:05:21+02:00 systemd[1]: snap.security-bear.security-bear.service: Start request repeated too quickly.
2021-12-30T20:05:21+02:00 systemd[1]: snap.security-bear.security-bear.service: Failed with result 'exit-code'.
2021-12-30T20:05:21+02:00 systemd[1]: Failed to start Service for snap application security-bear.security-bear.

```

**Comment by guyluz11** [comment]
https://forum.snapcraft.io/t/request-auto-connect-network-control-or-network-observe-for-security-bear/28112

**Comment by guyluz11** [comment]
Permission to use `network-observe` plug got approved.
This should solve this issue, please reopen if the same error return.
